### ISSUE TITLE
改成bachelor不能编译

### ISSUE THREAD

**Issue by lovecp3** [japinl/swust-thesis#5]
改成bachelor不能编译，只有一页空白
![Uploading 企业微信截图_20220219181946.png…]()
改成这样 \documentclass[bachelor]{swustthesis}

**Comment by japinli** [comment]
我这边看不到你的截图，我在 [Overleaf 上面是可以编译的](https://www.overleaf.com/read/cfzntcfqgswz)。
不知道是不是由于版本的问题导致的，有错误日志吗？

**Comment by lovecp3** [comment]
之前也是在overleaf不行的，用你给的这个可以，谢谢哈~
